blank_issues_enabled: false
contact_links:
  - name: Download latest firmware release
    url: https://github.com/INVESTEGATE/Prusa-MK3.5-MK3.5S-Custom-Firmware/releases/
    about: Download the latest tested BBF firmware release here.
  - name: Official Prusa custom firmware flashing instructions
    url: https://help.prusa3d.com/article/flashing-custom-firmware-core-one-l-core-one-mk4-s-mk3-9-s-mk3-5-s_814967
    about: Read this before flashing unofficial custom firmware.
  - name: INVESTEGATE Blog
    url: https://investegate.de/blog
    about: Related articles, guides and 3D printing projects.
